### ISSUE TITLE
Library organization?

### ISSUE THREAD

**Issue by aolofsson** [The-OpenROAD-Project/asap7#1]
What is the motivation for splitting the library into separate categories (buffer, ff, ao, ...). Usually stdlibs are organized per vt by not broken down into sub category inside each vt family...although sometimes there can be specialty libraries for ECOs, optimization, and power management.

**Comment by vvashish** [comment]
Classifying the cells into separate categories facilitated debugging when a certain type of cell failed during characterization without interrupting the characterization of other cell types not associated with the failing cell category. An unintended consequence of separating the liberty files in this manner has been that it allowed us to circumvent the Github imposed size limit of 100 MB for an individual file. Some of the CCS liberty files are quite large and concatenating these files by Vt types will result in a file exceeding the allowed size limit.
