### ISSUE TITLE
Some standard cells are not LVS clean

### ISSUE THREAD

**Issue by harrisonliew** [The-OpenROAD-Project/asap7#13]
I ran LVS on each cell contained in `GDS/asap7sc7p5t_27_R_201211.gds` against `CDL/LVS/asap7sc7p5t_27_R.cdl` and found these cells to be incorrect with the separately downloaded Calibre LVS deck:

- AND4x1
- SDFLx2
- AO21x1
- XOR2x2
- OAI31xp33
- OAI221xp5
- SDFLx3
- SDFLx1
- AOI211xp5
- OAI322xp33
- OR2x6
- A2O1A1O1Ixp25
- XNOR2x1
- OAI32xp33
- FAx1
- OAI21x1
- OAI31xp67
- OAI33xp33
- AO21x2
- AOI32xp33

For context, I dumped the list of cells from the GDS to a loop running LVS as a batch job, grepping for "INCORRECT" in the LVS log. The deck is set to virtually connect the substrate layers with `VIRTUAL CONNECT NAME "VDD" "VSS"`. The resulting output is attached (the cell name prior to the grep output is incorrect), and excluding these cells from the VLSI flow yields an LVS correct database.
[stdcells_lvs.txt](https://github.com/The-OpenROAD-Project/asap7/files/6911544/stdcells_lvs.txt)

**Comment by vvashish** [comment]
Hi @harrisonliew, 

I hope that you are doing well. I ran LVS on all the cells that you listed and found them to be clean. The LVS reports for all these cells are in the file attached here. 

I am uncertain, but I am wondering whether setting the switch 'LVS RECOGNIZE GATES' to  'ALL ' may be of help. The Calibre runset provided with the PDK should have contained all the correct options, so I am unsure what may have went wrong at your end. The reduction options (listed in the attached report) may also be worth looking at. 

[asap7sc7p5t_27_R_lvs_recheck_211119a.txt](https://github.com/The-OpenROAD-Project/asap7/files/7573498/asap7sc7p5t_27_R_lvs_recheck_211119a.txt)
