### ISSUE TITLE
What does the category (SIMPLE, SRAM...) on std lib stand for?

### ISSUE THREAD

**Issue by Waxpple** [The-OpenROAD-Project/asap7#15]
Hi, 

I do get some idea on the naming rule like 
1. LVT,RVT stands for threshold voltage.
2. AOI => And-Or-Inv
3. INV => inverter
But what does SRAM or SIMPLE mean?
Is there any explaination on naming rules?

Thanks!

Best regards,
Ethan

**Comment by maliberty** [comment]
sram = static random access memory (the acronym is more common)
simple = simple cells (nand, nor, and, or, xor, xnor)

I don't know of any document.
