### ISSUE TITLE
Request for ASAP7 Calibre Decks

### ISSUE THREAD

**Issue by baichen318** [The-OpenROAD-Project/asap7#16]
Hi all,

I recently applied for the request of ASAP7 Calibre Decks (https://live-predictive-pdk.pantheonsite.io/download/) with my university email account.

However, I could not get a response after submitting my application for several weeks.

I wondered how I could get access to ASAP7 Calibre Decks.

Thank you very much!

Best regards,
Chen

**Comment by Waxpple** [comment]
Me too. I want to access the deck too

**Comment by mi-and-core** [comment]
(encrypted) ASAP7 Calibre Decks: 
https://live-predictive-pdk.pantheonsite.io/download/

**Comment by 1bing2** [comment]
Me too. I want to access the deck too

**Comment by 1bing2** [comment]
> Me too. I want to access the deck too

Have you handle it ?

**Comment by tspyrou** [comment]
@vvashish can you help point people to a contact at ASU?

**Comment by 1bing2** [comment]
> @vvashish can you help point people to a contact at ASU?
Hello,
I wondered how I could get access to ASAP7 Calibre Decks. Have you handle it?
Thank you!

**Comment by vvashish** [comment]
Hi,

Apologies for the late reply. These messages went to my spam folder and I
just saw them. Prof. Lawrence T. Clark ***@***.***) would be
the best point of contact. He will be able to help with the Calibre deck
downloads.

Regards,
Vinay Vashishtha

**Comment by 1bing2** [comment]
Can you give me the email of Prof. Lawrence T.I want to contact him for thr Calibre Decks! 
My email is bingli226@mail.ustc.edu.cn

**Comment by vvashish** [comment]
***@***.***

On Sun, May 29, 2022 at 7:25 PM 1bing2 ***@***.***> wrote:

> Can you give me the email of Prof. Lawrence T.I want to contact him for
> thr Calibre Decks!
> My email is ***@***.***
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>
-- 
Regards,
Vinay Vashishtha

**Comment by idwwwoqq808** [comment]
> Can you give me the email of Prof. Lawrence T.I want to contact him for thr Calibre Decks! My email is [bingli226@mail.ustc.edu.cn](mailto:bingli226@mail.ustc.edu.cn)

I think this is the professor vvashish mentioned: https://search.asu.edu/profile/751415
