### ISSUE TITLE
Question about LIB model

### ISSUE THREAD

**Issue by pacificwind** [The-OpenROAD-Project/asap7#21]
Hi, I have a question about the type of LIB model.

When I go to the asap7/asap7sc7p5t_28/LIB/CCS directory,
there are three types of LIB files: CCS, CCSA, and CCSN.
What is the difference between those types?

The URL of the directory is as follows:
https://github.com/The-OpenROAD-Project/asap7/tree/master/asap7sc7p5t_28/LIB/CCS

**Comment by maliberty** [comment]
@tspyrou do you know?

**Comment by pacificwind** [comment]
It seems that CCSN means CCS-Noise.

![image](https://user-images.githubusercontent.com/89288774/167437797-a91e89c3-dcec-4649-b5cf-8cdddae05f7a.png)

It is in the 242-page of this manual.
https://picture.iczhiku.com/resource/eetop/shigyATqwoLuLmXv.pdf
