### ISSUE TITLE
Question about the Antenna Rule

### ISSUE THREAD

**Issue by pacificwind** [The-OpenROAD-Project/asap7#23]
Hi, I'd like to ask about the process antenna rule of ASAP7 PDK.

I'm currently trying to do APR with ASAP7 PDK.
And I'd like to check the process antenna rule for the APR, but I couldn't do it.
Does the ASAP7 PDK provide the information for the antenna rule? If it is, can I ask where it is (LEF file, LIB file...)?

**Comment by maliberty** [comment]
My recollection is that it has no antenna rules but @vvashish could confirm.

**Comment by vvashish** [comment]
That is correct, ASAP7 does not have any antenna rules.

Regards,
Vinay Vashishtha
