### ISSUE TITLE
When top routing layer is set above M7 - Innovus routing is not converging. 

### ISSUE THREAD

**Issue by sakundu** [The-OpenROAD-Project/asap7#25]
For the Ariane test case given [here](https://github.com/TILOS-AI-Institute/MacroPlacement/tree/main/Flows/ASAP7/ariane136), when we set the top routing layer to M8 or above layers, the P&R run never finishes. But when we set the top routing layer to M7, the P&R ends in a reasonable time. It would be great if the tool could utilize the M8-M9 layers.

**Comment by snpagliarini** [comment]
My understanding is that M8/M9 are not meant for signal routing. They are too thick. You should restrict signal routing to M7 and below
