### ISSUE TITLE
Scaled issue when streaming into virtuoso

### ISSUE THREAD

**Issue by zhengyue08** [The-OpenROAD-Project/asap7#27]
Hi, I met the scaled issue when streaming gds from innovus to virtuoso. I used 0.25 scale and 4000 db when streaming into virtuoso (4000db stream out). Most of layout looks right but M5_M4, M4_M3, M6_M5 didn't scale correctly. Like in the figure. Does anyone have idea about how to resolve it?

![Screenshot 2024-04-03 at 12 00 09 PM](https://github.com/The-OpenROAD-Project/asap7/assets/57664875/51fda2cd-47ba-4766-95ca-ed5e5dedf65a)

**Comment by maliberty** [comment]
asap7 is at
```
UNITS
 DATABASE MICRONS 1000 ;
END UNITS
```

**Comment by maliberty** [comment]
Unless you are using the 4x version

**Comment by zhengyue08** [comment]
Seems the lef file provided for us to do APR in innovus is 4x version. 
```
UNITS
 DATABASE MICRONS 4000 ;
END UNITS
MANUFACTURINGGRID 0.004
```
I'm in the university so maybe we don't have the license to do APR on 1x version.

So is it possible to stream the 4x gds from innovus into virtuoso correctly?

**Comment by maliberty** [comment]
We can't support proprietary tools but I would expect it to work as gds is a standard format.

**Comment by zhengyue08** [comment]
Thank you. So which environment do you usually use this PDK? Does OpenLane fully support conducting APR on 1x version? Or if you usually use cadence toolset, could you guide me how to check if my environment can allow me to conduct APR on 1x version?

**Comment by maliberty** [comment]
Again I can provide no guidance on proprietary tools.  https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts supports asap7.

**Comment by zhengyue08** [comment]
Sure sure, thank you.
