### ISSUE TITLE
Difference between version 27 and 28

### ISSUE THREAD

**Issue by gilgamsh** [The-OpenROAD-Project/asap7#28]
I use `diff` to check the difference between asap7 7,5t version 27 and 28. And I find that only some slight changes happen, such as numbers in spacing tables. 
I am wondering is there any desciption about the difference about asap7 version 27 and 28

**Comment by maliberty** [comment]
Not to my knowledge.  I think 28 was some bug fixes but they creators didn't do incremental releases and just pushed out a whole new version.

**Comment by gilgamsh** [comment]
> Not to my knowledge. I think 28 was some bug fixes but they creators didn't do incremental releases and just pushed out a whole new version.

May I know OpenROAD-flow-scripts use which version now?

**Comment by maliberty** [comment]
> May I know OpenROAD-flow-scripts use which version now?

28

**Comment by maliberty** [comment]
You can see it in the file names, eg asap7sc7p5t_**28**_L_1x_220121a.lef

**Comment by gilgamsh** [comment]
Thank you for your reply. And I am also interested in whether asap7 6 track version and the sram have been tested or tried with OpenROAD-flow-scripts.

**Comment by maliberty** [comment]
Neither is used in ORFS.   Its possible some experiments were done in the past but I don't have any data.
