### ISSUE TITLE
Why we need 4x lef?

### ISSUE THREAD

**Issue by gilgamsh** [The-OpenROAD-Project/asap7#29]
I'm new in the area, and I'm wondering why we need 4x scaled lef. It seems like everything multiple 4 (16 for area.)

And I find that at here https://github.com/The-OpenROAD-Project/asap7sc7p5t_28/blob/d88477438935a5a388bd6294f682dc405c93c5d2/techlef_misc/asap7_tech_4x_201209.lef#L383

The `MAXIMUMDENSITY 360`  which violate the lef requirements follows:
```
MAXIMUMDENSITY maxDensity

Specifies the maximum metal density allowed for the layer, as a percentage. The minDensity and maxDensity values represent the metal density range within which all areas of the design must fall. The metal density must be greater than or equal to minDensity and less than or equal to maxDensity.
Type: Float
Value: Between 0.0 and 100.0
```

**Comment by maliberty** [comment]
For some users of proprietary tools a extra license is needed for 7nm PDKs.  The 4X versions allow you to pretend this is 28nm if you lack such a license.  It is not needed for open source tools without such licensing requirements.
