### ISSUE TITLE
tech lef parasitics

### ISSUE THREAD

**Issue by hchenji** [The-OpenROAD-Project/asap7#35]
Pardon my ignorance, I don't work in this area. I'm trying to use ASAP7 in a mflowgen flow with synopsys DC for synthesis, which I want to run in topographical mode. Where do I get the resistance/capacitance for the tech lef layers? It can be in the lef or as a separate tluplus file I believe.

**Comment by rovinski** [comment]
This repository only has qrc tech files which are for use with Cadence flows. I am doubtful there is an easy way to translate from qrc to tluplus.

Some alternatives for reduced quality approximations are:
1. Generate a captable from the qrc tech file using Cadence tools. You should be able to translate this more easily to a Synopsys format.
2. Use the [setRC.tcl](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/99af1aca7b0b7c835f95f16c401716134e154ec9/flow/platforms/asap7/setRC.tcl) from OpenROAD-flow-scripts to get per-unit resistances and capacitances. Note that these values are correlated values to openroad and may not represent the exact process parameters.
