### ISSUE TITLE
liberty files contain output to output timing arcs

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/asap7#38]
In https://github.com/The-OpenROAD-Project/OpenROAD/issues/2270 @jjcherry56 points out an issue with the ASAP7 liberty files. The `FAx1_ASAP7_75t_R` and `HAxp5_ASAP7_75t_R` cells have output to output timing arcs, eg:

```
  cell (FAx1_ASAP7_75t_R) {
...
    pin (CON) {
      direction : output;
...
    pin (SN) {
      direction : output;
...
      timing () {
        related_pin : "CON";
```

Are the liberty files auto generated or do we just make edits, re-compress and submit a PR?

**Comment by tspyrou** [comment]
@antonblanchard you can edit and recompress and create a PR.

**Comment by maliberty** [comment]
@tspyrou edit in what way?  Removing the arcs will render the model incorrect as there will be no arcs to SN.

**Comment by jjcherry56** [comment]
@maliberty removing the arcs from CON to SN leaves the arcs from A, B and CI.

**Comment by maliberty** [comment]
Let's take HAxp5_ASAP7_75t_R since it is simpler.  I looked at the CDL at is basically:
![image](https://user-images.githubusercontent.com/761514/191090030-879436fe-d8ac-459f-adf5-d80aac322117.png)

(the right two gates are actually a single AOI but this was easier to draw).  I expect the A->SN path is the lower one and the A->CON->SN path is not covered by that arc.  Removing the CON->SN arc could lead to incorrect results.

**Comment by jjcherry56** [comment]
Then you are correct; they cannot be deleted. That is a really poorly designed cell that fails to buffer CON. The library should be using related_output_pin instead of output to output arcs but we can't easily fix it to combine the models.

**Comment by tspyrou** [comment]
How many cells are there like this? We could mark this at don't use. I am surprised to see an unbuffered path to CON in a new technology.

**Comment by maliberty** [comment]
The half and full adders would have to be disabled which isn't great.   I have no idea who designed the cells for this library.

**Comment by tspyrou** [comment]
I just talked to Cherry. I don't think we should try to fix this. OpenSTA supports it and the bug related to it in the fanout count was fixed.
