### ISSUE TITLE
Can I directly use this pdk in OpenLane flow?

### ISSUE THREAD

**Issue by hello-eternity** [The-OpenROAD-Project/asap7#45]
Now asap7 is supported by openroad, but now openlane has the process of starting from synthesis. Can you tell me how to use openlane to support asap7 and what is the plan of openroad？

**Comment by vijayank88** [comment]
@hello-eternity 
OpenROAD-flow-scripts already has support
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/8307935f0f186cbfea4cc14dcbd17a0c9c8fafd1/flow/Makefile#L69

**Comment by vijayank88** [comment]
For OpenLane support track this issue: https://github.com/The-OpenROAD-Project/OpenLane/issues/666
