### ISSUE TITLE
please open the road

### ISSUE THREAD

**Issue by anishsheikh** [The-OpenROAD-Project/asap7#46]
please clear the roadblocks my friends from uni tried to acquire the calibre decks but stuck in potholes of ignorance. it would be great if you guys clear the roads from unneccesary roadblocks

**Comment by maliberty** [comment]
It is explained on the front page:
![image](https://user-images.githubusercontent.com/761514/221047398-74cd5b3c-547e-48fd-8e0b-94853ecbb9f6.png)

Do you need something else?

**Comment by anishsheikh** [comment]
well, we have already filled out it couple of times, I tried my personal email that didn't work, my friends tried their school emails, still nothing, some of them actually wrote to prof, Lawdence which, the same result. should i fill it out again with my personal email or school email because my school doesn't provide an .edu or school email my friends does.

**Comment by vvashish** [comment]
> well, we have already filled out it couple of times, I tried my personal email that didn't work, my friends tried their school emails, still nothing, some of them actually wrote to prof, Lawdence which, the same result. should i fill it out again with my personal email or school email because my school doesn't provide an .edu or school email my friends does.

Hi @anishsheikh. Sorry about this. It seems that we missed your email. Please email Prof. Clark again at lawrence.clark@asu.edu and cc me (vvashish@asu.edu). I will ensure that he does not miss it again. Be sure to use your University or work email address and to list your university/company affiliation.

**Comment by anishsheikh** [comment]
thank you for help, my friend mailed from kiit.ac.in
