### ISSUE TITLE
Can you upload the ASAP7 6T unscaled qrcTechFile and 1X techLEF file?

### ISSUE THREAD

**Issue by doo3yoon** [The-OpenROAD-Project/asap7#48]
For ASAP7 7p5T, I can download the unscaled qrcTechFile and 1X techLEF file. 
But I cannot find them from the 6T category.
Can you upload them?

**Comment by maliberty** [comment]
Proprietary data can't be uploaded so no to the qrcTechFile.  You can get the 1x data from https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/tree/master/flow/platforms/asap7/lef
