### ISSUE TITLE
Request for ASAP7 Calibre Decks 

### ISSUE THREAD

**Issue by 1864mp** [The-OpenROAD-Project/asap7#56]
Hi I've requested a week ago calibre decks only I have had no reply - are the decks available to British universities? I can't see why not ARM was a British company afterall. Perhaps the link is dead?

**Comment by maliberty** [comment]
I've tried sending a message to Prof. Clark on your behalf but that's all I can do.

**Comment by 1864mp** [comment]
> I've tried sending a message to Prof. Clark on your behalf but that's all I can do.

thanks, hopefully that'll get things going.

**Comment by maliberty** [comment]
Please send me your email here or by DM on slack so I can pass it along.

**Comment by 1864mp** [comment]
hello that's mpanovic@ee.ucl.ac.uk 
thanks.

**Comment by mrc-donato** [comment]
> Please send me your email here or by DM on slack so I can pass it along.

Hi, I've also been trying to access the calibre decks. Would you mind sending me a copy as well? Thanks!

**Comment by maliberty** [comment]
Have you put in a request through https://asap.asu.edu/download/ ?

**Comment by mrc-donato** [comment]
Yes, I submitted a request last week but haven't received a reply yet

**Comment by maliberty** [comment]
Let me know you email here or an DM on slack if you prefer.
